### ISSUE TITLE
export resources only

### ISSUE THREAD

**Issue by TankTheFrank** [cocos2d/creator_to_cocos2dx#129]
We need a "build resources only" option in creator, as it is now "build" also overwrites the reader c++ code leading to rebuilding source code that is not really changed and overwriting any changes made to that code.

**Comment by minggo** [comment]
Yep, it is a reasonable requirement.

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/creator_to_cocos2dx/pull/131
