### ISSUE TITLE
plugin blending of Sprite is different from cocosCreator

### ISSUE THREAD

**Issue by jusforfun** [cocos2d/creator_to_cocos2dx#138]
Hi  minggo,

Have used the plugin to export from Cocos Creator to cocos2d-x but after exporting, i am having issues with how the sprites is blending;
Blending set in cocos creator SrcBlend : SRC_ALPHA , DstBlend: ONE_MINUS_SRC_ALPHA

**Comment by jusforfun** [comment]
![cloudblendingcomparison](https://user-images.githubusercontent.com/33598173/35212825-6849d148-ff96-11e7-8de0-d355a2063935.PNG)
This is the comparison picture where left part where it is weird is in cocos2dx and the right is in cocos creator

**Comment by minggo** [comment]
Thanks for reporting the issue. Could you please provide a creator project to reproduce it?

**Comment by jusforfun** [comment]
[SampleCocosCreatorProj.zip](https://github.com/cocos2d/creator_to_cocos2dx/files/1654152/SampleCocosCreatorProj.zip)

Attached is a sample

**Comment by minggo** [comment]
Thanks, i will take a look ASAP though i am busy with new renderer.

**Comment by jusforfun** [comment]
Alright. Hope to hear from you soon! Thanks!

**Comment by minggo** [comment]
Yep, i can reproduce it. I think it is caused by alpha blending. Creator don't premultiply alpha but cocos2d-x does. I will look into how to fix it.

**Comment by minggo** [comment]
@jusforfun i think it is fixed in https://github.com/cocos2d/creator_to_cocos2dx/pull/140, could you please have a test and give some feedback, thanks.

**Comment by jusforfun** [comment]
@minggo yes it seems to be fixed; Thanks so much
Will close this for now; Will update you if i encounter any similar issue again.

**Comment by minggo** [comment]
thanks for report
