### ISSUE TITLE
Export all resources including not used in any Scene

### ISSUE THREAD

**Issue by minggo** [cocos2d/creator_to_cocos2dx#141]
There may have some resources that are not used in any Scene, but may be used in run time. So there should have an option to do it.

**Comment by drelaptop** [comment]
what's the resources may used in run time? from the [creator docs](http://docs.cocos.com/creator/manual/zh/scripting/load-assets.html?h=resource), I know the this type res is located at `assets/resources`

> 动态加载
Creator provides cc.loader.loadRes the API to load specific Asset that is located under the Resources directory. And cc.loader.load difference is that loadRes should only load a single Asset. Invoke, you only need to pass a relative path to the resources, and Not at the end of the path containing the file name extension.
动态加载资源要注意两点，一是所有需要通过脚本动态加载的资源，都必须放置在 resources 文件夹或它的子文件夹下。resources 需要在 assets 文件夹中手工创建，并且必须位于 assets 的根目录，就像这样：

So, to finished this feature, we need to add a option in the plugin panel, and then copy the `resources` folder into the corresponding location depend on the option value, is it right? @minggo

**Comment by minggo** [comment]
Yep, need to add an option to do it. You should discuss with creator team about where to copy the resources.
