### ISSUE TITLE
CreatorReader::createWithFilename   cannot be resolved

### ISSUE THREAD

**Issue by tianxiao875** [cocos2d/creator_to_cocos2dx#148]
Seriousness code indicates that the project file line is forbidden to display
External symbol "error LNK2019 public: static class creator: could not parse: CreatorReader * __cdecl creator: createWithFilename (class: CreatorReader:: std:: basic_string<char, struct: std: char_traits<char>, class std:: const & allocator<char> >)" (? CreateWithFilename@CreatorReader@creator@@SAPAV12@ABV? $basic_string@DU? $char_traits@D@std@@V? $allocator@D@2@@std@@@Z), the symbol "public: void __thiscall HelloWorld: in function: menuCloseCallback (class cocos2d:: Ref *)" (? MenuCloseCallback@HelloWorld@@QAEXPAVRef@cocos2d@@@Z) cited myGame D:\\cocosGameProjects\\myGame\\proj.win32\\HelloWorldScene.obj 1

**Comment by tianxiao875** [comment]
vs 2017    I've added the reader project directory to the additional dependency directory. And determined
#include. Using CreatorReader:: createWithFilename is wrong

**Comment by minggo** [comment]
It is a link error, please make sure the reader files are added into project.

**Comment by tianxiao875** [comment]
I added a file directory connection. Let me look at it and see the official example

**Comment by tianxiao875** [comment]
我确定我是把reader 目录添加到了附加包含目录里面，代码也是你们实例的写法，还是不行。

**Comment by tianxiao875** [comment]
而且我把源码： NATIVE_PROJECT_ROOT/Classes/reader

资源： NATIVE_PROJECT_ROOT/Resources/creator  的文件删除之后，再次build 不会再生成。

**Comment by tianxiao875** [comment]
调用createWithFilename（“”）；的时候出现这个错;单单声明creator::CreatorReader*是正常的

**Comment by drelaptop** [comment]
@tianxiao875 http://forum.cocos.com/t/creator-to-cocos2dx/54981/7?u=2627993092 看这里有详细的步骤

**Comment by drelaptop** [comment]
answered, please close @minggo
