### ISSUE TITLE
AnimationClip wrap mode bug

### ISSUE THREAD

**Issue by jusforfun** [cocos2d/creator_to_cocos2dx#151]
@minggo 
On the creator_project grossini_dance_08_2's clip (AnimationClip2) setting the wrap mode to Reverse and exported out with plugin version #140;

There is a bug where animation Wrap mode will get read wrongly at the parseNodeAnimation for the rest of the wrapMode; Reverse gt read as integer 36 which pretty much went out of scope of the enum AnimationClip::WrapMode

**Comment by minggo** [comment]
Thanks for reporting the issue.
@drelaptop please take a look.

**Comment by drelaptop** [comment]
@jusforfun refer to #152 to fix this

**Comment by drelaptop** [comment]
fixed, please close @minggo
