### ISSUE TITLE
Animation is not exported completely

### ISSUE THREAD

**Issue by hlhtddx** [cocos2d/creator_to_cocos2dx#179]
I add an animation to a sprite and try to export the project to cocos2dx cpp project. I checked the output, but cannot find the clips of animation. It seems only the clips' name are recorded. However the .anim files are missed.

**Comment by jusforfun** [comment]
@hlhtddx  If this helps,

To my understanding, the animation clip information is embeded into the flatbuffer file exported (someSceneFile.ccreator)

To use the animation, you could play the animation clip with the clip name using playAnimationClip method in AnimationManager
