### ISSUE TITLE
弱弱地问一下，是不是CreatorReaderBinding.h被移除了？

### ISSUE THREAD

**Issue by yuangu** [cocos2d/creator_to_cocos2dx#57]
如题，CreatorReaderBinding.h被移除了，是不是lua bind这块自己用tolua++导出

**Comment by minggo** [comment]
It is [here](https://github.com/cocos2d/creator_to_cocos2dx/blob/master/creator_project/packages/creator-luacpp-support/reader/CreatorReader_generated.h). I haven't updated lua-binding codes, i will do it after it is stable. But i think currently it is enough to use.

And please use english in future. Thanks.
