### ISSUE TITLE
PageView page size issue

### ISSUE THREAD

**Issue by minggo** [cocos2d/creator_to_cocos2dx#59]
Now PageView's page size is the same as PageView's size, so background may be hidden by pages. Should change it to make sure that page size can not be equal with PageView's size.

**Comment by ggsnail** [comment]
好像有个拼写错误？

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/creator_to_cocos2dx/pull/61

@ggsnail what's your meaning? And please use english, thanks.
