### ISSUE TITLE
Toggle error

### ISSUE THREAD

**Issue by qmqsyz** [cocos2d/creator_to_cocos2dx#67]
when build, there is error:
creator-luacpp-support\core\parser\Toggle.js:31 Uncaught TypeError: Cannot read property '__id__' of undefined

Toggle.js
30:        // CheckMark
31:        let checkmark_id = background_node_data._children[0].__id__;

**Comment by minggo** [comment]
Could you please provide the creator project to reproduce the issue? Thanks.

**Comment by jake22599** [comment]
#70, unknownly, i created a new issue ticket with the project files and screen shot.

**Comment by minggo** [comment]
thanks, so i close this one.
