### ISSUE TITLE
The widget component does not align properly

### ISSUE THREAD

**Issue by jake22599** [cocos2d/creator_to_cocos2dx#69]
I tried to convert a simple test ui project with widget to align ui elements to the side of the screen. But when i use the parser and try in on the native cpp project. it does not show up properly.
I'm using the 0.2 release.

Attached is a cocos creator project with 9 ui elements align to the corners.
[creator_project.zip](https://github.com/cocos2d/creator_to_cocos2dx/files/1213554/creator_project.zip)

**Comment by minggo** [comment]
thanks

**Comment by minggo** [comment]
There is not problem, i think it is fixed in https://github.com/cocos2d/creator_to_cocos2dx/pull/73. You can get latest plugin to have a try.
