### ISSUE TITLE
Crash when parsing Toggle and Toggle group ui element

### ISSUE THREAD

**Issue by jake22599** [cocos2d/creator_to_cocos2dx#70]
It crashes while the project is compile and it show that the check mark id is undefined.
I'm using the example project.

Attached is the screen shot and the project.
![-2017-08-11 16_26_25](https://user-images.githubusercontent.com/685223/29207134-9bf46da6-7eb7-11e7-9abb-debf077afc19.jpg)
[creator_project.zip](https://github.com/cocos2d/creator_to_cocos2dx/files/1217362/creator_project.zip)

**Comment by minggo** [comment]
thanks

**Comment by minggo** [comment]
`checkmask` should be child of `background` or the plugin can not find it. It is a limitation, but there is not solution for it. Because there is not information about which  node is the `checkmask`.

Why you need to modify it to make `checkmask` as a child of `Toggle` directly?

**Comment by jake22599** [comment]
I did not modify anything while creating the toggle items. I just create the default toggle item template.

**Comment by minggo** [comment]
What's your creator version?

**Comment by minggo** [comment]
I found Creator 1.5.2 changes the node structure. I used Creator 1.4.2, i am not sure if i should change to support only 1.5.2+.

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/creator_to_cocos2dx/pull/77

**Comment by jake22599** [comment]
1.5.2
