### ISSUE TITLE
Node with Widget component will be ignore when parse

### ISSUE THREAD

**Issue by kudo108** [cocos2d/creator_to_cocos2dx#8]
- I create a Node in Canvas
- add to Node a Widget component, set some fixed value to widget
- add some button or sprite into node
- run on Creator: ok
- build & run to cocos2dx project (cpp): node not visible 

//// If remove Widget component: that node run normally

**Comment by minggo** [comment]
@kudo108 could you please share your creator project?
Thanks.

**Comment by minggo** [comment]
I think it is fixed.
