### ISSUE TITLE
Incorrect assets filenames

### ISSUE THREAD

**Issue by xdeadmonkx** [cocos2d/creator_to_cocos2dx#82]
Hello, my C++ Android project cannot load ccreator scene due to incorrect filenames inside ccreator file, for example - creator/image\default_btn_disabled.png (may be due to different slashes)
it is simple scene with default button inside

ConvertFileToJson.js
```
    if (assetpath[-1] != '/')
        assetpath += '/';
```
:)

**Comment by minggo** [comment]
Did you test on windows? And could you please provide a creator project to test?

**Comment by jamesbake** [comment]
我也遇到这个问题了, 廖大能不能在setupSpriteFrames把filename转换成linux格式的

**Comment by minggo** [comment]
please use english in future, and only me work in this repo currently

**Comment by jamesbake** [comment]
thanks for reminding me, but my english is so poor, the question is that i can't use your plugin to create scene on android device, this maybe is the path problem

**Comment by minggo** [comment]
No, you english is good. Yep, i will translate all paths to linux format, but i have to reproduce the issue first.

**Comment by jamesbake** [comment]
alright, i use your plugin with cocos engine 3.15 and the cocoscreator official website said more than 3.14 versions can be used, you can try it when you have time

**Comment by jamesbake** [comment]
i debug it with vs2013, the function Sprite::setSpriteFrame parameter is like 'resources\\xx.png'

**Comment by minggo** [comment]
thanks, i will try it on windows tomorrow

**Comment by minggo** [comment]
@jamesbake i tested with VS2015, don't find problem with resource path.

**Comment by jamesbake** [comment]
sorry, i'm late, i use cocoscreator 1.6 and the cocos engine is 3.15.1, When I modify the CreatorReader:: setupSpriteFrames () use replace \\ with /, it runs normally, but some control like Toggle can't be selected, has not any touch event, some control like button show two in the canvas, should i choose cocostudio instead of cocoscreator?

**Comment by jamesbake** [comment]
i think you use cocoscreator with low version, and the output file with suffix ccreator has correct path to read  when the function CreatorReader:createWithFilename is called

**Comment by minggo** [comment]
Yep, i used creator lower than 1.6. I will try 1.6.

**Comment by minggo** [comment]
@jamesbake i used creator 1.6 to test, there is not problem. And i set a breakpoint in `CreatorReader::setupSpriteFrames()`, the filename doesn't include `\`.

>  but some control like Toggle can't be selected, has not any touch event, some control like button show two in the canvas

Will you please provide a creator project to reproduce it? Thanks.

**Comment by sit17** [comment]
I have some problem, and what i do just relpace "\\" to "/" when saveing json file.

**Comment by minggo** [comment]
@sit17 why not send a PR for it?

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/creator_to_cocos2dx/pull/100
