### ISSUE TITLE
Cocos2dx UI Delegates

### ISSUE THREAD

**Issue by jake22599** [cocos2d/creator_to_cocos2dx#83]
Will there be improvements to the code to allow us to set delegates while the ui element is created.
Currently, i have to either 
- manually loop through each ui element and check the name for the item element and dynamic cast it to the cocos2dx class type for me to set the delegate or the listener callbacks.
- override the current [CreatorReader] class to add virtual over each ui element creation function. And override the [CreatorReader] with a custom class to handle each ui element delegate assignments.

For example, the Button callback, Scroll view delegate, EditBox delegate, etc... To name a few.
Will there be a way to allow those customization in the plans?

**Comment by minggo** [comment]
No, there is not plan. It is just a scene editor, when parsing a scene, the reader doesn't know the delegate, delegate is game logic specific.
