### ISSUE TITLE
Android Studio compile wrong

### ISSUE THREAD

**Issue by TristenChenTao** [cocos2d/creator_to_cocos2dx#89]
Android Studio 2.3.3
MacOS 10.12.6
Cocos2dx 3.15.1
 i can successfully run same project in xcode, but in android studio compile wrong

my Android.mk
![333](https://user-images.githubusercontent.com/2186895/29766189-816ceaf6-8c10-11e7-981d-f659b0f455f8.png)

error message is 
![4444](https://user-images.githubusercontent.com/2186895/29766203-8986fed4-8c10-11e7-93c4-43b61cb4619b.png)

**Comment by minggo** [comment]
I haven't tried Android Studio 2.3.3, i will try it. Currently, you can just remove `ProcessCpuTracker.cpp` from `cocos/platform/android/Android.mk` to fix it. It is nothing about the plugin.

**Comment by TristenChenTao** [comment]
thanks , i remove ProcessCpuTracker and then another error  appear 
![555](https://user-images.githubusercontent.com/2186895/29768629-957c163a-8c19-11e7-803e-f186ac682e07.png)
please guide me thanks

**Comment by minggo** [comment]
It seems Android Studio 2.3.3 doesn't support android-13. You can change `PROP_COMPILE_SDK_VERSION=13` to `PROP_COMPILE_SDK_VERSION=14` in `PROJECT_ROOT/gradle.properties`.

**Comment by TristenChenTao** [comment]
i try and  error message is
![6666](https://user-images.githubusercontent.com/2186895/29769311-674c0772-8c1c-11e7-9b22-953189a8c4e6.png)


External Native Build Issues
Build command failed.
Error while executing process /Users/TristenChenTao/MacInstall/Android/SDK/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/TristenChenTao/Downloads/HelloWorldDemo2/proj.android-studio/app/jni/Android.mk NDK_APPLICATION_MK=/Users/TristenChenTao/Downloads/HelloWorldDemo2/proj.android-studio/app/jni/Application.mk APP_ABI=armeabi NDK_ALL_ABIS=armeabi NDK_DEBUG=0 APP_PLATFORM=android-9 NDK_OUT=/Users/TristenChenTao/AndroidRamDisk/proj.android-studio/HelloWorldDemo2/intermediates/ndkBuild/release/obj NDK_LIBS_OUT=/Users/TristenChenTao/AndroidRamDisk/proj.android-studio/HelloWorldDemo2/intermediates/ndkBuild/release/lib NDK_TOOLCHAIN_VERSION=4.9 APP_PLATFORM=android-14 NDK_MODULE_PATH=/Users/TristenChenTao/Downloads/HelloWorldDemo2/cocos2d:/Users/TristenChenTao/Downloads/HelloWorldDemo2/cocos2d/cocos:/Users/TristenChenTao/Downloads/HelloWorldDemo2/cocos2d/external -j8 NDK_DEBUG=0 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
rm -f /Users/TristenChenTao/AndroidRamDisk/proj.android-studio/HelloWorldDemo2/intermediates/ndkBuild/release/lib/armeabi/*
rm -f /Users/TristenChenTao/AndroidRamDisk/proj.android-studio/HelloWorldDemo2/intermediates/ndkBuild/release/lib/armeabi/gdbserver
rm -f /Users/TristenChenTao/AndroidRamDisk/proj.android-studio/HelloWorldDemo2/intermediates/ndkBuild/release/lib/armeabi/gdb.setup
mkdir -p /Users/TristenChenTao/AndroidRamDisk/proj.android-studio/HelloWorldDemo2/intermediates/ndkBuild/release/obj/local/armeabi/objs/MyGame_shared/hellocpp
echo [armeabi] "Compile++ thumb": "MyGame_shared <= main.cpp"

**Comment by minggo** [comment]
Hi, i asked to modify `PROP_COMPILE_SDK_VERSION=14`, not `PROP_TARGET_SDK_VERSION`.

**Comment by TristenChenTao** [comment]
![77777](https://user-images.githubusercontent.com/2186895/29803061-f7d3edca-8cab-11e7-840c-ea9e4d823e4e.png)

no more error "Android NDK: android-13 is unsupported. Using minimum supported version android-14. "

but still other error
![999](https://user-images.githubusercontent.com/2186895/29803089-20be0914-8cac-11e7-8553-fa12f4e1ea9b.png)


External Native Build Issues
Build command failed.
Error while executing process /Users/TristenChenTao/MacInstall/Android/SDK/ndk-bundle/ndk-build with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=/Users/TristenChenTao/Downloads/HelloWorldDemo/proj.android-studio/app/jni/Android.mk NDK_APPLICATION_MK=/Users/TristenChenTao/Downloads/HelloWorldDemo/proj.android-studio/app/jni/Application.mk APP_ABI=armeabi NDK_ALL_ABIS=armeabi NDK_DEBUG=1 APP_PLATFORM=android-9 NDK_OUT=/Users/TristenChenTao/AndroidRamDisk/proj.android-studio/HelloWorldDemo/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=/Users/TristenChenTao/AndroidRamDisk/proj.android-studio/HelloWorldDemo/intermediates/ndkBuild/debug/lib NDK_TOOLCHAIN_VERSION=4.9 APP_PLATFORM=android-14 NDK_MODULE_PATH=/Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d:/Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/cocos:/Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/external -j8 NDK_DEBUG=1 APP_SHORT_COMMANDS=false LOCAL_SHORT_COMMANDS=false -B -n}
rm -f /Users/TristenChenTao/AndroidRamDisk/proj.android-studio/HelloWorldDemo/intermediates/ndkBuild/debug/lib/armeabi/*
rm -f /Users/TristenChenTao/AndroidRamDisk/proj.android-studio/HelloWorldDemo/intermediates/ndkBuild/debug/lib/armeabi/gdbserver
rm -f /Users/TristenChenTao/AndroidRamDisk/proj.android-studio/HelloWorldDemo/intermediates/ndkBuild/debug/lib/armeabi/gdb.setup
mkdir -p /Users/TristenChenTao/AndroidRamDisk/proj.android-studio/HelloWorldDemo/intermediates/ndkBuild/debug/lib/armeabi
echo [armeabi] "Gdbserver      ": "[arm-linux-androideabi-4.9] /Users/TristenChenTao/AndroidRamDisk/proj.android-studio/HelloWorldDemo/intermediates/ndkBuild/debug/lib/armeabi/gdbserver"
install -p /Users/TristenChenTao/MacInstall/Android/SDK/ndk-bundle/prebuilt/android-arm/gdbserver/gdbserver /Users/TristenChenTao/AndroidRamDisk/proj.android-studio/HelloWorldDemo/intermediates/ndkBuild/debug/lib/armeabi/gdbserver
echo [armeabi] "Gdbsetup       ": "/Users/TristenChenTao/AndroidRamDisk/proj.android-studio/HelloWorldDemo/intermediates/ndkBuild/debug/lib/armeabi/gdb.setup"
echo "set solib-search-path /Users/TristenChenTao/AndroidRamDisk/proj.android-studio/HelloWorldDemo/intermediates/ndkBuild/debug/obj/local/armeabi" > /Users/TristenChenTao/AndroidRamDisk/proj.android-studio/HelloWorldDemo/intermediates/ndkBuild/debug/lib/armeabi/gdb.setup
echo "directory /Users/TristenChenTao/MacInstall/Android/SDK/ndk-bundle/sysroot /Users/TristenChenTao/Downloads/HelloWorldDemo/proj.android-studio/app/jni/../../../Classes /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/cocos/./../../Classes/reader/. /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/cocos/editor-support/cocostudio/.. /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/cocos/editor-support/cocosbuilder/.. /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/cocos/3d/.. /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/cocos/editor-support/spine/.. /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/cocos/ui/../editor-support /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/cocos/audio/android/../include /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/external/flatbuffers/.. /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/extensions/. /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/extensions/.. /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/extensions/GUI/CCControlExtension /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/extensions/GUI/CCScrollView /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/external/Box2D/.. /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/cocos/network /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/external/android-specific/pvmp3dec/src /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/external/android-specific/pvmp3dec/include /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/cocos/./../external /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/cocos/./../external/tinyxml2 /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/cocos/./../external/unzip /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/cocos/./../external/chipmunk/include/chipmunk /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/cocos/./../external/xxhash /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/cocos/./../external/nslog /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/cocos/./../external/poly2tri /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/cocos/./../external/poly2tri/common /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/cocos/./../external/poly2tri/sweep /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/cocos/./../external/clipper /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/external/websockets/prebuilt/android/../../include/android /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/external/freetype2/prebuilt/android/../../include/android /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/external/freetype2/prebuilt/android/../../include/android/freetype2 /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/external/png/prebuilt/android/../../include/android /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/external/jpeg/prebuilt/android/../../include/android /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/external/tiff/prebuilt/android/../../include/android /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/external/webp/prebuilt/android/../../include/android /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/external/chipmunk/prebuilt/android/../../include /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/external/zlib/prebuilt/android/../../include /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/external/recast/.. /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/external/bullet/.. /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/cocos/platform/android /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/external/openssl/prebuilt/android/../../include/android /Users/TristenChenTao/MacInstall/Android/SDK/ndk-bundle/sources/android/cpufeatures /Users/TristenChenTao/MacInstall/Android/SDK/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include /Users/TristenChenTao/MacInstall/Android/SDK/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi/include /Users/TristenChenTao/MacInstall/Android/SDK/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/backward /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/cocos/audio/android/../.. /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/cocos/audio/android/../../platform/android /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/cocos/audio/android/../../../external/android-specific /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/cocos/./../external/edtaa3func /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/cocos/./../external/ConvertUTF /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/cocos/platform/android/.. /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/cocos/platform/android/../.. /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/cocos/platform/android/../../../external /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/cocos/editor-support/cocosbuilder/../../2d /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/cocos/editor-support/cocostudio/WidgetReader /Users/TristenChenTao/Downloads/HelloWorldDemo/cocos2d/external/android-specific/tremolo/Tremolo" >> /Users/TristenChenTao/AndroidRamDisk/proj.android-studio/HelloWorldDemo/intermediates/ndkBuild/debug/lib/armeabi/gdb.setup
mkdir -p /Users/TristenChenTao/AndroidRamDisk/proj.android-studio/HelloWorldDemo/intermediates/ndkBuild/debug/obj/local/armeabi/objs-debug/MyGame_shared/hellocpp
echo [armeabi] "Compile++ thumb": "MyGame_shared <= main.cpp"

**Comment by minggo** [comment]
I am busy with dragonbones support, i will take a look ASAP.

**Comment by TristenChenTao** [comment]
OK， i wait you response, thanks

**Comment by minggo** [comment]
i think it is fixed in latest version 0.3.
