### ISSUE TITLE
Exporting Prefab issue when the root is simple cc.Node.

### ISSUE THREAD

**Issue by celp** [cocos2d/creator_to_cocos2dx#90]
Hello, thank you so much for supporting cpp.

I got the error below when exporting auto-synced prefab.
`Prefab.js: Uncaught TypeError: Cannot set property 'contentSize' of undefined`
And I found the error occurred when prefab's root is simple `cc.Node` (with no component).

I think the reason is the code below in `Prefab.js`.

```
    _adjust_properties(original_properties, name) {
        let node_properties = this._properties.node;
```

Simple `cc.Node` doesn't have property `node`.
So I think it needs conditional branch like below.

```
    _adjust_properties_for_simple_node_root(original_properties, name) {
        this._properties[name] = original_properties[name];
    }
```

Regards,

**Comment by minggo** [comment]
Could you please provide a creator project to reproduce it, thanks.

**Comment by celp** [comment]
Sure.
I have created `node-prefab` and added to `prefab-test` scene only. 

[20170831_creator_to_cocos2dx-master.zip](https://github.com/cocos2d/creator_to_cocos2dx/files/1265879/20170831_creator_to_cocos2dx-master.zip)

**Comment by minggo** [comment]
Thanks, fixed in https://github.com/cocos2d/creator_to_cocos2dx/pull/93.
